export type JobStatus = 'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected';

export interface JobApplication {
  id: string;
  company: string;
  role: string;
  jobDescription: string;
  status: JobStatus;
  dateAdded: number;
  dateUpdated: number;
  salary?: string;
  url?: string;
  location?: string;
  
  // Artifacts
  resumeId: string; // ID of the specific resume snapshot for this job
  coverLetter?: string;
  
  // Interview Prep
  interviewQuestions?: string[]; // Generated by AI
  notes?: string;
}